image: docker:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - apk add --no-cache python py2-pip
  - pip install --no-cache-dir docker-compose==1.12.0
  - docker-compose -v

stages:
  - test

test:
  stage: test
  script:
    - docker-compose -f ci-composer.yml up --build -d
    - docker-compose -f ci-composer.yml run app npm run test-all
    - docker-compose -f ci-composer.yml run api
    - docker-compose -f ci-composer.yml down
