image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test

test_api:
  stage: test
  script:
    - docker-compose -f ci-composer.yml pull api mongo
    - docker-compose -f ci-composer.yml build api
    - docker-compose -f ci-composer.yml run --rm -T api bundle exec rake test

test_app:
  stage: test
  script:
    - docker-compose -f ci-composer.yml pull
    - docker-compose -f ci-composer.yml build
    - docker-compose -f ci-composer.yml run --rm -T app npm run test-all
