version: '2'
services:
  asesora:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - './app/public:/usr/share/nginx/html'
      - './app/conf/nginx.conf:/etc/nginx/nginx.conf'

  selenium:
    image: selenium/standalone-chrome
    environment:
      - JAVA_OPTS=-Dselenium.LOGGER.level=WARNING
    links:
      - asesora
    ports:
      - '4444:4444'

  app:
    build: ./app
    environment:
      - API_HOST=api
      - API_PORT=4567
    volumes:
      - './app/public:/test/public'
    depends_on:
      - asesora
      - api
      - selenium

  api:
    build: ./api
    environment:
      - API_HOST=api
      - API_PORT=4567
      - MONGODB_URI=mongodb://mongo:27017/db
    ports:
      - '4567:4567'
    links:
      - mongo
    command: sh -c 'rackup config.dev.ru --port 4567 -o 0.0.0.0'

  mongo:
    image: mongo
    environment:
      - AUTH=no
    ports:
      - 27017:27017

volumes:
  bundle:
    driver: local
