---
- hosts: all
  become: yes
  connection: ssh
  vars_files:
    - environment/all_variables.yml

  pre_tasks:
    - name: test python and install (dependency for ansible)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
  - include: tasks/db_create_a_directory_for_backup_in_remote.yml
  - include: tasks/db_mongo_dump.yml
  - include: tasks/db_compress_database_to_a_file.yml
  - include: tasks/db_download_file.yml
  - include: tasks/db_delete_temporary_data.yml
