---
- hosts: all
  become: yes
  connection: ssh
  vars_files:
    - environment/all_variables.yml

  pre_tasks:
    - name: test python and install (dependency for ansible)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
  - name: create a directory for mongodb backup
    file:
      path: "{{ tmp_folder }}/backup"
      state: directory
      recurse: yes
      owner: mongodb
      group: mongodb

  - name: Mongo Dump
    command: mongodump --db {{ mongo_ddbb }} --out "{{ tmp_folder }}/backup"

  - name: Create a bz2 archive of backup
    archive:
      path:
      - "{{ tmp_folder }}/backup"
      dest: "{{ tmp_folder }}/backup_asesora.tar.bz2"
      format: bz2
  - name: download file
    fetch:
      src: "{{ tmp_folder }}/backup_asesora.tar.bz2"
      dest: backup/backup_asesora.tar.bz2
      flat: yes
  - name: delete directory of mongodb backup
    file:
      path: "{{ tmp_folder }}/backup/"
      state: absent
  - name: delete file of mongodb backup
    file:
      path: "{{ tmp_folder }}/backup_asesora.tar.bz2"
      state: absent
