---
- hosts: all
  become: yes
  connection: ssh
  vars_files:
    - environment/all_variables.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  pre_tasks:
      - name: remove and create now the staging folder
        local_action:
          module: script
          _raw_params: "scripts/clean_staging.sh"
      - name: build a new app for staging
        local_action:
          module: script
          _raw_params: "scripts/docker_build.sh"
      - name: copy app to staging folder
        local_action:
          module: script
          _raw_params: "scripts/copy_app_to_staging_folder.sh"

- name: a play that runs entirely on the remote
  hosts: digitalocean
  connection: ssh
  tasks:
    - name: test python and install (dependency for ansible)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - include: tasks/upload_asesora_folder.yml
    - include: tasks/disable_asesora_site.yml
    - include: tasks/move_asesora_folder.yml
    - include: tasks/enable_site_asesora.yml
