---
- hosts: all
  become: yes
  connection: ssh
  vars_files:
    - environment/all_variables.yml

  pre_tasks:
    - name: test python and install (dependency for ansible)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: add repository for use mongodb
      apt_repository:
        repo: deb http://ftp.debian.org/debian jessie-backports main
        state: present

    - name: update&upgrade system
      apt:
        update_cache: yes
        upgrade: dist
    - name: remove old ruby
      apt:
        name: ruby
        state: absent
    - name: remove asesora.conf if exist before their installation
      file:
        path: "/etc/apache2/sites-enabled/010-asesora.conf"
        state: absent

    - name: Check if new ruby is installed (from residual installation)
      command: ruby -v
      register: ruby

    - include: tasks/dependencies_for_all.yml
    - include: tasks/dependencies_for_ruby.yml
    - include: tasks/install_ruby_2-5-1.yml
      when: ruby.stdout.find('ruby 2.5.1') == 1

  tasks:
    - include: tasks/install_mongodb.yml
    - include: tasks/install_apache2.yml
    - include: tasks/install_phusionpassenger.yml
    - include: tasks/update_bashrc.yml
    - include: tasks/update_envvars_apache2.yml
    - include: tasks/disable_default_site.yml
    - include: tasks/enable_site_asesora.yml
