---
- hosts: all
  become: yes
  connection: ssh
  vars_files:
    - environment/all_variables.yml

  pre_tasks:
    - name: test python and install (dependency for ansible)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:

  - name: create a directory for mongodb backup
    file:
      path: "{{ tmp_folder }}/backup"
      state: directory
      recurse: yes
      owner: mongodb
      group: mongodb
  - name: upload file
    copy:
      src: backup/backup_asesora.tar.bz2
      dest: "/tmp/backup_asesora.tar.bz2"
  - name: download and extract ruby 2.5.1
    unarchive:
      copy: no
      src: "/tmp/backup_asesora.tar.bz2"
      dest: "/tmp"
      owner: mongodb
      group: mongodb

  - name: Mongo Restore
    command: mongorestore --drop --db {{ mongo_ddbb }} "{{ tmp_folder }}/backup"

  - name: delete directory of mongodb backup
    file:
      path: "{{ tmp_folder }}/backup/"
      state: absent
  - name: delete file of mongodb backup
    file:
      path: "{{ tmp_folder }}/backup_asesora.tar.bz2"
      state: absent
