---
- hosts: all
  become: yes
  connection: ssh
  vars_files:
    - environment/all_variables.yml

  pre_tasks:
    - name: test python and install (dependency for ansible)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  tasks:
    - include: tasks/upload_asesora_folder.yml
    - include: tasks/disable_asesora_site.yml
    - include: tasks/move_asesora_folder.yml
    - include: tasks/enable_site_asesora.yml
