
export let SolicitudeModel = {
  labels: {
    "analysis": "",
    "applicant": "",
    "date": "",
    "applicantEmail": "",
    "applicantPhonenumber": "",
    "applicantName": "",
    "applicantSurname": "",
    "text": "",
    "noDate": "",
    "addSubject": "",
    "company": "",
    "companyName": "",
    "companyCif": "",
    "companyEmployees": "",
    "companyCnae": "",
    "noContact": "",
    "incompleteCompanyIdentity": "",
    "noCompanyName": "",
    "suggestions" : "",
    "submit" : "",
    "editCompany":"",
    "editCompany":"",
    "editingCompany": "",
    "submitting" : "",
    "editiondiscard" : "",
    "editionsubmit" : "",
    "editionsubmitting" : "",
    "deleteSolicitude" : "",
    "errorPhone": "",
    "errorEmail": "",
    "errorEmail": "",
    "proposals": "",
    "proposals": "",
    "topics": "",
    "topics": "",
    "sent": "",
    "subjectsList": "",
    "subjectsList": "",
    "addValue": "",
    "addValue": "",
    "addedEmployeesValueMessage": "",
    "addedNameValueMessage": "",
    "companyInfo": "",
    "companyInfo": "",
    "submittoSubject": "",
    "submittoSubject": "",
    "editionsubmittoSubject": "",
    "editionsubmittoSubject": "",
    "notApply": "",
    "subject": "",
    "subject": "",
    "modifySubject": "",
    "modifySubject": "",
    "subjectModified": "",
    "subjectModified": "",
    "modify": "",
    "modify": "",
    "ccaa": "",
    "ccaa": "",
    "personalData": "",
    "personalData": "",
    "contactData": "",
    "contactData": "",
    "solicitudeData": "",
    "solicitudeData": "",
    "solicitude": "",
    "solicitude": "",
    "identification": "",
    "identification": "",
    "information": "",
    "information": "",
    "description": "",
    "description": "",
    "placeholderdescription": "",
    "placeholderdescription": "",
    "comments": ""
  },
  values: {
    "text": "",
    "text": "",
    "date": "",
    "id": "",
    "applicantName": "",
    "applicantSurname": "",
    "applicantEmail": "",
    "applicantPhonenumber": "",
    "applicantId": "",
    "applicantCcaa": "",
    "companyName": "",
    "companyCif": "",
    "companyEmployees": "",
    "companyCnae": "",
    "suggestions" : "",
    "subjects": [],
    "proposals": [],
    "analysis": "",
    "selectedTopics": [],
    "subjectId": "",
    "description": "",
    "comments": ""
  },
  ccaaCatalog: [],
  suggestedCompanies: [],
  suggestedApplicants: [],
  fullfilled: false,
  fullfilledToAddSubject: false,
  isValidCif: true,
  cnaeCatalog:[],
  isValidCompanyIdentity: true,
  isValidCompanyName: true,
  isValidContact: true,
  submittable: false,
  showAlert: true,
  showUpdatedEmployeesValueMessage: false,
  showUpdatedNameValueMessage: false,
  editionmode: false,
  editCompany: false,
  showEditCompanyButton: false,
  saveCompany: false,
  isValidPhone: true,
  isValidEmail: true,
  topicsCatalog: [],
  proposalsCatalog: [],
  editionSubject: false,
  modifiedSubjectId: 0,
  translate:function(key,value) {
    this.labels[key] = value
  },
  setValues:function(key, value) {
    this.values[key] = value
  },
  cloneValues:function(){
    let clone = Object.assign({}, this.values)
    return clone
  }
}
