---
- name: stop service mongodb
  service:
    name: mongodb
    state: stopped
- name: create a directory for mongodb data
  file:
    path: "{{ mongo_data }}"
    state: directory
    recurse: yes
    owner: mongodb
    group: mongodb
- name: update bind_ip
  replace:
    path: /etc/mongodb.conf
    regexp: '(\#?)bind_ip(.*)'
    replace: 'bind_ip = {{ mongo_ip }}'
    backup: yes
- name: update port
  replace:
    path: /etc/mongodb.conf
    regexp: '(\#?)port(.*)'
    replace: 'port = {{ mongo_port }}'
    backup: yes
- name: update dbpath
  replace:
    path: /etc/mongodb.conf
    regexp: '(\#?)dbpath(.*)'
    replace: 'dbpath = {{ mongo_data }}'
    backup: yes
- name: start service mongodb
  service:
    name: mongodb
    state: started
