---
- name: create directory for mongodb
  become: yes
  file:
    dest: "{{ mongo_data_folder }}"
    owner: mongodb
    group: mongodb
    recurse: yes
- name: copy config file for mongodb
  copy:
    src: "files/mongodb.conf"
    dest: "/etc/mongodb.conf"
- name: update bind_ip
  replace:
    path: /etc/mongodb.conf
    regexp: 'bind_ip(.*)'
    replace: 'bind_ip = {{ mongo_ip }}'
    backup: yes
- name: update port
  replace:
    path: /etc/mongodb.conf
    regexp: 'port(.*)'
    replace: 'port = {{ mongo_port }}'
    backup: yes
- name: update dbpath
  replace:
    path: /etc/mongodb.conf
    regexp: 'dbpath(.*)'
    replace: 'dbpath = {{ mongo_data_folder }}'
    backup: yes

- name: install mongodb
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    install_recommends: yes
  vars:
    packages:
    - mongodb
