---
- name: create directory for mongodb
  become: yes
  file:
    dest: "{{ mongo_data }}"
    owner: mongodb
    group: mongodb
    recurse: yes

- name: copy config file for mongodb
  copy:
    src: "files/mongodb.conf"
    dest: "/etc/mongodb.conf"
- name: install mongodb
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    install_recommends: yes
  vars:
    packages:
    - mongodb
