---
- name: delete old environment variables from .bashrc
  become: yes
  lineinfile:
    dest: /root/.bashrc
    regexp: "export {{ item }}=(.*)"
    state: absent
  with_items:
    - API_HOST
    - API_PORT
    - MONGODB_URI
- name: add new lines at end of .bashrc
  become: yes
  lineinfile:
    path: /root/.bashrc
    line: "{{ item }}"
  with_items:
    - "export API_HOST={{ api_host }}"
    - "export API_PORT={{ api_port }}"
    - "export MONGODB_URI=mongodb://{{ mongo_ip }}:{{ mongo_port }}/{{ ddbb_name }}"
- name: update environment variables
  become: yes
  shell: "source /root/.bashrc"
  args:
    executable: /bin/bash
