---
- name: update envvars apache2
  lineinfile:
    path: "/etc/apache2/envvars"
    line: "{{ item }}"
  with_items:
    - "export RUBY_ENV=$(which ruby)"
    - "export ASESORA_PATH='/var/www/asesora'"
    - "export API_HOST={{ api_host }}"
    - "export API_PORT={{ api_port }}"
    - "export MONGODB_URI=mongodb://{{ mongo_ip }}:{{ mongo_port }}{{ mongo_ddbb }}"
